### ISSUE TITLE
SQL Injection possible

### ISSUE THREAD

**Issue by RyderAsKing** [GallearTech/VexPanel#1]
https://github.com/GallearTech/VexPanel/blob/9f1ebf8b0ed32350cfe5505ab9aafb00c24fd503/discord.php#L62
It does nothing to protect the password. From security standpoint, it is exactly the same as storing it without any encoding.
base64 is a encoding method which can be decoded easily.

SQL Injection is easily possible in all the /api files
Example line - $checkDB = $conn->query("SELECT * FROM users WHERE discord_id='".$_GET['did']."'");

**Comment by SonDerpy** [comment]
Hey, Ryder! I've already mentioned this problem to him, he said he is going to add more "encryption later".
      - Exact message: I'll be adding more encryption later on, but at least it's more encrypted
Which I do not clearly understand, because passwords are meant to be hashed.

**Comment by The-MG** [comment]
Hello Ryder! Thanks for the heads up. And I already know that it's not the best type of encryption. I've already planned to change the account details method, but haven't had time. I'm currently not at my office and I won't be until Sunday afternoon Pacific Time. Until then I can only do minimal edits. I will be fixing this ASAP though.
 ~MG
