### ISSUE TITLE
Issue when changing the copyright

### ISSUE THREAD

**Issue by knifeworm** [GallearTech/VexPanel#2]
Hello so i am trying to change the Copyright © 2021 Gallear Technologies.
thing to Copyright © 2021 Leetnodes.

But when i change it and safe the file it is still there

is there a way to fix this

thanks
knifeworm

**Comment by The-MG** [comment]
Hello @knifeworm! 

Thanks for the information. I will be running some tests on this within the next hour. If I'm able to change it without any errors, then it would most likely be within your end (cache). 

Thanks,
Gallear Technologies.

**Comment by knifeworm** [comment]
Ok thank you very much i will try clearing my cache to see if that works

**Comment by knifeworm** [comment]
> Ok thank you very much i will try clearing my cache to see if that works

Clearing my cache has also not worked.

**Comment by The-MG** [comment]
Alright, ran a test, and it worked. The footer changed. So it's most likely on your servers end, or your client end. If you are using cloud-flare, you might want to clear the cache on that. If none of these work, you can probably just wait a few hours. I'm not familiar on how often cache updates, but DNS can take up to 48 hours to update. 

Thanks,
Gallear Technologies.

**Comment by SuperS123** [comment]
_thats not how copyrights work_
