### ISSUE TITLE
can't figure out how to get past login page and vexpanel doesn't update database.

### ISSUE THREAD

**Issue by AltyS-CZ** [GallearTech/VexPanel#4]
I'm trying to use vexpanel on localhost and so far i can get to http://localhost/login.php
My problem is that i look in my database and go to users and there isn't anything there.
I also can't figure out the oauth url
I've tried everything. index.php, 404 and 500.php, account etc

I need help using this on localhost

**Comment by The-MG** [comment]
Hello @AltyS-CZ ! I'm sorry to hear about your issue. However, we have recently released notes about completely re-doing our systems. That being said, once we get v1 out, things will be much easier to setup, reconfigure, and so much more.

Thanks,
MG
