### ISSUE TITLE
ERR 404 while ordering a server

### ISSUE THREAD

**Issue by OceanTechnic** [GallearTech/VexPanel#6]
`Fatal error: Uncaught HCGCloud\Pterodactyl\Exceptions\NotFoundException: The resource you are looking for could not be found. in /www/wwwroot/domain/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php:123 Stack trace: #0 /www/wwwroot/domain/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php(102): HCGCloud\Pterodactyl\Pterodactyl->handleRequestError() #1 /www/wwwroot/domain/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php(23): HCGCloud\Pterodactyl\Pterodactyl->request() #2 /www/wwwroot/domain/vendor/hcgcloud/pterodactyl-sdk/src/Actions/ManagesEggs.php(32): HCGCloud\Pterodactyl\Pterodactyl->get() #3 /www/wwwroot/domain/inc/buy.php(55): HCGCloud\Pterodactyl\Pterodactyl->egg() #4 {main} thrown in /www/wwwroot/domain/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php on line 123`

The config correct I have checked it more times.

**Comment by The-MG** [comment]
You most likely don't have your egg variables defined correctly. 

Thanks,
Administration Team.
