### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by knifeworm** [GallearTech/VexPanel#7]
Hello so i am using ur panel but when i click authorize with the discord it just sends me back to the same discord page

**Comment by dotargz** [comment]
Did you even read the readme?

**Comment by The-MG** [comment]
> Hello so i am using ur panel but when i click authorize with the discord it just sends me back to the same discord page

Hello! I'm very thankful for your support. But, as noted in the readme, we are not supporting Vex Panel v0.x.x anymore. If you want more information, you can join our [Discord server](https://discord.gg/JpZmtYRWYN) at anytime. 

Thanks,
Administration Team!
